apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lu3j
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0048-tenant/ci10t-776-0048-app/devfile-sample-lu3j@sha256:fa3a3b78db46d484af27db141c25209f147b4c7c6b99eb77d2bb3394f558d0c6
        name: my-nodejs
        resources: {}
status: {}
